version: '3'

x-lagoon-project:
  # Lagoon project name (leave `&lagoon-project` when you edit this)
  &lagoon-project laravel-example-simple

x-volumes:
  &default-volumes
    # Define all volumes you would like to have real-time mounted into the docker containers
    volumes:
      - .:/app:delegated

x-environment:
  &default-environment
    LAGOON_PROJECT: *lagoon-project
    # Route that should be used locally, if you are using pygmy, this route *must* end with .docker.amazee.io
    LAGOON_ROUTE: &default-url http://${COMPOSE_PROJECT_NAME:-laravel-example-simple}.docker.amazee.io
    # Uncomment if you like to have the system behave like in production
    #LAGOON_ENVIRONMENT_TYPE: production
    # Uncomment to enable xdebug and then restart via `docker-compose up -d`
    #XDEBUG_ENABLE: "true"

x-user:
  &default-user
    # The default user under which the containers should run. Change this if you are on linux and run with another user than id `1000`
    user: '1000'


services:
  cli: # cli container
    build:
      context: .
      dockerfile: lagoon/cli.dockerfile
    image: &cli-image ${COMPOSE_PROJECT_NAME:-laravel-example-simple}-cli # this image will be reused as `CLI_IMAGE` in subsequent Docker builds
    labels:
      # Lagoon Labels
      lagoon.type: cli-persistent
      lagoon.persistent.name: nginx # mount the persistent storage of nginx into this container
      lagoon.persistent: /app/storage/ # location where the persistent storage should be mounted
      lando.type: 'php-cli'
    << : *default-volumes # loads the defined volumes from the top
    user: root
    volumes_from: # mount the ssh-agent from the pygmy or cachalot ssh-agent
      - container:amazeeio-ssh-agent
    environment:
      << : *default-environment # loads the defined environment variables from the top
    depends_on:
        - mariadb

  nginx:
    build:
      context: .
      dockerfile: lagoon/nginx.dockerfile
      args:
        CLI_IMAGE: *cli-image # Inject the name of the cli image
    labels:
      lagoon.type: nginx-php-persistent
      lagoon.persistent: /app/storage/ # define where the persistent storage should be mounted too
      lando.type: 'nginx'
    << : [*default-volumes, *default-user] # loads the defined volumes and user from the top
    depends_on:
      - cli # basically just tells docker-compose to build the cli first
    environment:
      << : *default-environment # loads the defined environment variables from the top
      LAGOON_LOCALDEV_URL: *default-url # generate another route for nginx, by default we go to varnish
    networks:
      - amazeeio-network
      - default

  php:
    build:
      context: .
      dockerfile: lagoon/php.dockerfile
      args:
        CLI_IMAGE: *cli-image
    labels:
      lagoon.type: nginx-php-persistent
      lagoon.name: nginx # we want this service be part of the nginx pod in Lagoon
      lagoon.persistent: /app/storage/ # define where the persistent storage should be mounted too
      lando.type: 'php-fpm'
    << : [*default-volumes, *default-user] # loads the defined volumes and user from the top
    depends_on:
      - cli # basically just tells docker-compose to build the cli first
    environment:
      << : *default-environment # loads the defined environment variables from the top

  mariadb:
    image: uselagoon/mariadb
    labels:
      lagoon.type: mariadb
      lando.type: mariadb
    ports:
      - "3306" # exposes the port 3306 with a random local port, find it with `docker-compose port mariadb 3306`
    << : *default-user # uses the defined user from top
    environment:
      << : *default-environment

  redis:
    image: uselagoon/redis
    labels:
      lagoon.type: redis
      lando.type: redis
    << : *default-user # uses the defined user from top
    environment:
      << : *default-environment

#  elasticsearch:
#    image: uselagoon/elasticsearch-7
#    labels:
#      lagoon.type: elasticsearch
#      lando.type: elasticsearch
#    << : *default-user # uses the defined user from top
#    environment:
#      << : *default-environment

#  solr:
#    build:
#      context: .
#      dockerfile: lagoon/solr.dockerfile
#    labels:
#      lagoon.type: solr
#      lando.type: solr
#    ports:
#      - "8983" # exposes the port 8983 with a random local port, find it with `docker-compose port solr 8983`
#    depends_on:
#      - cli
#    environment:
#      << : *default-environment

networks:
  amazeeio-network:
    external: true
